--[[rpr_atlantis-Lua Upgrade]]--

function InitGame(levelTime, randomSeed, restart)  
	game.Print("Initializing Lua Map Upgrade ..."); 
	game.Print("-map_restart ..."); 
		game.Print("--workaround-setup ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "target_levelchange");
				ent:SetKeyValue("targetname", "map_restart");
				ent:SetKeyValue("target", "rpg_atlantis");
				entity.CallSpawn(ent);
		game.Print("--trigger-setup ...");
			if restart == 1 then
				game.ClientPrint(-1, "Please don't use map_restart, use map or devmap instead.");
				game.Print("Please don't use map_restart, use map or devmap instead.");
				ent = entity.Find("map_restart")
				entity.Use(ent)
			end
	game.Print("-Adding Transporter with UI ...");
		game.Print("--redirecting usable ...");
			ent = entity.FindBModel(241);
			ent:SetKeyValue("target", "tr_ui");
			entity.CallSpawn(ent);
		game.Print("--setting up trigger ...");
			ent = entity.Spawn();
			mover.SetPosition(ent, -600, 1528, -560);
			ent.SetupTrigger(ent, 192, 192, 96);
			ent:SetKeyValue("classname", "trigger_transporter");
			ent:SetKeyValue("wait", "5");
			ent:SetKeyValue("targetname", "tr_trigger");
			entity.CallSpawn(ent);
		game.Print("--setting up UI ...");
			ent = entity.Spawn();
			ent:SetKeyValue("classname", "ui_transporter");
			ent:SetKeyValue("targetname", "tr_ui");
			ent:SetKeyValue("target", "tr_trigger");
			entity.CallSpawn(ent);
	game.Print("-Adding weapon FX ...");
		game.Print("--usable setup ...");
			ent = entity.FindBModel(55);
			ent:SetKeyValue("target", "phaser-vfx");
			ent = entity.FindBModel(218);
			ent:SetKeyValue("target", "torpedo-vfx");
		game.Print("--Torpedo-Relay ...");
			ent = entity.Spawn();
			ent:SetKeyValue("classname", "target_relay");
			ent:SetKeyValue("target", "torpedo-vfx-relayed");
			ent:SetKeyValue("spawnflags", "8");
			ent:SetKeyValue("targetname", "torpedo-vfx");
			entity.CallSpawn(ent);
		game.Print("--Deck 1 ...");
			game.Print("---target setup ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "weapTrgD1");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, -248, -1040, -80);
			game.Print("---Phaser ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "fx_phaser");
				ent:SetKeyValue("target", "weapTrgD1");
				ent:SetKeyValue("targetname", "phaser-vfx");
				ent:SetKeyValue("wait", "3");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, -248, -304, -64);
			game.Print("---Torpedo ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "fx_torpedo");
				ent:SetKeyValue("target", "weapTrgD1");
				ent:SetKeyValue("wait", "1");
				ent:SetKeyValue("count", "500");
				ent:SetKeyValue("targetname", "torpedo-vfx");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, -248, -304, -96);
		game.Print("--Deck 2 ...");
			game.Print("---target setup ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "weapTrgD2");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, -278, -1016, -192);
			game.Print("---Phaser ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "fx_phaser");
				ent:SetKeyValue("target", "weapTrgD2");
				ent:SetKeyValue("targetname", "phaser-vfx");
				ent:SetKeyValue("wait", "3");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, -278, -256, -200);
			game.Print("---Torpedo ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "fx_torpedo");
				ent:SetKeyValue("target", "weapTrgD2");
				ent:SetKeyValue("wait", "1");
				ent:SetKeyValue("count", "500");
				ent:SetKeyValue("targetname", "torpedo-vfx-relayed");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, -278, -256, -208);
		game.Print("--Deck 3 ...");
			game.Print("---target setup ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "weapTrgD3");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, -387, -592, -600);
			game.Print("---Phaser ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "fx_phaser");
				ent:SetKeyValue("target", "weapTrgD3");
				ent:SetKeyValue("targetname", "phaser-vfx");
				ent:SetKeyValue("wait", "3");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, -387, 120, -432);
			game.Print("---Torpedo ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "fx_torpedo");
				ent:SetKeyValue("target", "weapTrgD3");
				ent:SetKeyValue("wait", "1");
				ent:SetKeyValue("count", "500");
				ent:SetKeyValue("targetname", "torpedo-vfx-relayed");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, -387, 120, -464);
	game.Print("... done.");
end