--rpg_magnificent Lua Upgrade
--by Harry Young

function InitGame(levelTime, randomSeed, restart)
	game.Print("Lua Level Init...");
	game.Print("-map_restart ...");
		game.Print("--workaround-setup ...");
			ent = entity.Spawn();
			ent:SetKeyValue("classname", "target_levelchange");
			ent:SetKeyValue("targetname", "map_restart");
			ent:SetKeyValue("target", "rpg_magnificent");
			entity.CallSpawn(ent);
		game.Print("--trigger-setup ...");
		if restart == 1 then
			game.ClientPrint(-1, "Please don't use map_restart, use map or devmap instead.");
			game.Print("Please don't use map_restart, use map or devmap instead.");
			ent = entity.Find("map_restart")
			entity.Use(ent)
		end
	game.Print("-Setting up spawnpoints...");
		entity.RemoveSpawns();
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "info_player_start");
		ent:SetKeyValue("targetname", "Transporter Room");
		mover.SetPosition(ent, -144, -2880, 3832);
		mover.SetAngles(ent, 0, 180, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "info_player_start");
		ent:SetKeyValue("targetname", "Transporter Room");
		mover.SetPosition(ent, -212, -2880, 3832);
		mover.SetAngles(ent, 0, 180, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "info_player_start");
		ent:SetKeyValue("targetname", "Transporter Room");
		mover.SetPosition(ent, -280, -2880, 3832);
		mover.SetAngles(ent, 0, 180, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "info_player_start");
		ent:SetKeyValue("targetname", "Transporter Room");
		mover.SetPosition(ent, -176, -2824, 3832);
		mover.SetAngles(ent, 0, 180, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "info_player_start");
		ent:SetKeyValue("targetname", "Transporter Room");
		mover.SetPosition(ent, -248, -2824, 3832);
		mover.SetAngles(ent, 0, 180, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "info_player_start");
		ent:SetKeyValue("targetname", "Transporter Room");
		mover.SetPosition(ent, -176, -2936, 3832);
		mover.SetAngles(ent, 0, 180, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "info_player_start");
		ent:SetKeyValue("targetname", "Transporter Room");
		mover.SetPosition(ent, -248, -2936, 3832);
		mover.SetAngles(ent, 0, 180, 0);
		entity.CallSpawn(ent);
	game.Print("-Adding Transporter with UI ...");
		game.Print("--Transporter Room ...");
			game.Print("---redirecting usable ...");
				ent = entity.FindBModel(74);
				ent:SetKeyValue("target", "tr_ui-tr");
				entity.CallSpawn(ent);
			game.Print("---setting up trigger ...");
				ent = entity.Spawn();
				mover.SetPosition(ent, -208, -2880, 3860);
				ent.SetupTrigger(ent, 192, 192, 104);
				ent:SetKeyValue("classname", "trigger_transporter");
				ent:SetKeyValue("wait", "5");
				ent:SetKeyValue("targetname", "tr_trigger-tr");
				entity.CallSpawn(ent);
			game.Print("---setting up UI ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "ui_transporter");
				ent:SetKeyValue("targetname", "tr_ui-tr");
				ent:SetKeyValue("target", "tr_trigger-tr");
				entity.CallSpawn(ent);
			game.Print("---Clean-Up previous System ...");
				ent = entity.Find("t399");
				ent.Lock(ent);
		game.Print("--Cargobay ...");
			game.Print("---redirecting usable ...");
				ent = entity.FindBModel(68);
				ent:SetKeyValue("target", "tr_ui-cb");
				entity.CallSpawn(ent);
			game.Print("---setting up trigger ...");
				ent = entity.Spawn();
				mover.SetPosition(ent, -2264, -1496, 4220);
				ent.SetupTrigger(ent, 96, 96, 104);
				ent:SetKeyValue("classname", "trigger_transporter");
				ent:SetKeyValue("wait", "5");
				ent:SetKeyValue("targetname", "tr_trigger-cb");
				entity.CallSpawn(ent);
			game.Print("---setting up UI ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "ui_transporter");
				ent:SetKeyValue("targetname", "tr_ui-cb");
				ent:SetKeyValue("target", "tr_trigger-cb");
				entity.CallSpawn(ent);
			game.Print("---Clean-Up previous System ...");
				ent = entity.Find("t417");
				ent.Lock(ent);
			game.Print("---prep beam-ins ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Cargobay");
				mover.SetPosition(ent, -2256, -1496, 4172);
				mover.SetAngles(ent, 0, 270, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Cargobay");
				mover.SetPosition(ent, -2280, -1520, 4172);
				mover.SetAngles(ent, 0, 270, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Cargobay");
				mover.SetPosition(ent, -2280, -1472, 4172);
				mover.SetAngles(ent, 0, 270, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Cargobay");
				mover.SetPosition(ent, -2232, -1520, 4172);
				mover.SetAngles(ent, 0, 270, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Cargobay");
				mover.SetPosition(ent, -2232, -1472, 4172);
				mover.SetAngles(ent, 0, 270, 0);
				entity.CallSpawn(ent);
		game.Print("--Shuttlebay ...");
			game.Print("---redirecting usable ...");
				ent = entity.FindBModel(66);
				ent:SetKeyValue("target", "tr_ui-sb");
				entity.CallSpawn(ent);
			game.Print("---setting up trigger ...");
				ent = entity.Spawn();
				mover.SetPosition(ent, -3448, -1480, 4036);
				ent.SetupTrigger(ent, 96, 96, 104);
				ent:SetKeyValue("classname", "trigger_transporter");
				ent:SetKeyValue("wait", "5");
				ent:SetKeyValue("targetname", "tr_trigger-sb");
				entity.CallSpawn(ent);
			game.Print("---setting up UI ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "ui_transporter");
				ent:SetKeyValue("targetname", "tr_ui-sb");
				ent:SetKeyValue("target", "tr_trigger-sb");
				entity.CallSpawn(ent);
			game.Print("---Clean-Up previous System ...");
				ent = entity.Find("t436");
				ent.Lock(ent);
			game.Print("---prep beam-ins ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Shuttlebay");
				mover.SetPosition(ent, -3448, -1480, 3988);
				mover.SetAngles(ent, 0, 180, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Shuttlebay");
				mover.SetPosition(ent, -3472, -1504, 3988);
				mover.SetAngles(ent, 0, 180, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Shuttlebay");
				mover.SetPosition(ent, -3472, -1456, 3988);
				mover.SetAngles(ent, 0, 180, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Shuttlebay");
				mover.SetPosition(ent, -3424, -1504, 3988);
				mover.SetAngles(ent, 0, 180, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Shuttlebay");
				mover.SetPosition(ent, -3424, -1456, 3988);
				mover.SetAngles(ent, 0, 180, 0);
				entity.CallSpawn(ent);
		game.Print("--Asteroidbase ...");
			game.Print("---redirecting usable ...");
				ent = entity.FindBModel(1);
				ent:SetKeyValue("target", "tr_ui-ab");
				entity.CallSpawn(ent);
			game.Print("---setting up trigger ...");
				ent = entity.Spawn();
				mover.SetPosition(ent, -2272, 1692, 4992);
				ent.SetupTrigger(ent, 160, 136, 160);
				ent:SetKeyValue("classname", "trigger_transporter");
				ent:SetKeyValue("wait", "5");
				ent:SetKeyValue("targetname", "tr_trigger-ab");
				entity.CallSpawn(ent);
			game.Print("---setting up UI ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "ui_transporter");
				ent:SetKeyValue("targetname", "tr_ui-ab");
				ent:SetKeyValue("target", "tr_trigger-ab");
				entity.CallSpawn(ent);
			game.Print("---Clean-Up previous System ...");
				ent = entity.Find("t530");
				ent.Lock(ent);
			game.Print("---prep beam-ins ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Asteroid Base - Transport Area");
				mover.SetPosition(ent, -2272, 1728, 4916);
				mover.SetAngles(ent, 0, 90, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Asteroid Base - Transport Area");
				mover.SetPosition(ent, -2248, 1696, 4916);
				mover.SetAngles(ent, 0, 90, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Asteroid Base - Transport Area");
				mover.SetPosition(ent, -2296, 1696, 4916);
				mover.SetAngles(ent, 0, 90, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Asteroid Base - Transport Area");
				mover.SetPosition(ent, -2232, 1664, 4916);
				mover.SetAngles(ent, 0, 90, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Asteroid Base - Transport Area");
				mover.SetPosition(ent, -2272, 1664, 4916);
				mover.SetAngles(ent, 0, 90, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Asteroid Base - Transport Area");
				mover.SetPosition(ent, -2312, 1632, 4916);
				mover.SetAngles(ent, 0, 90, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Asteroid Base - Transport Area");
				mover.SetPosition(ent, -2216, -1632, 4916);
				mover.SetAngles(ent, 0, 90, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Asteroid Base - Transport Area");
				mover.SetPosition(ent, -2256, -1632, 4916);
				mover.SetAngles(ent, 0, 90, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Asteroid Base - Transport Area");
				mover.SetPosition(ent, -2296, -1632, 4916);
				mover.SetAngles(ent, 0, 90, 0);
				entity.CallSpawn(ent);
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "Asteroid Base - Transport Area");
				mover.SetPosition(ent, -2328, -1632, 4916);
				mover.SetAngles(ent, 0, 90, 0);
				entity.CallSpawn(ent);
	--[[game.Print("-Setting up force fields...");
		game.Print("--Shuttlebay...");
			game.Print("---Port...");
				game.Print("----Converting...");
					ent = entity.FindBModel(110);
					ent:SetKeyValue("classname", "func_forcefield");
					ent:SetKeyValue("targetname", "sbportff");
					ent:SetKeyValue("wait", "200");
					entity.CallSpawn(ent);
				game.Print("----setting up relay...");
					ent = entity.Spawn();
					ent:SetKeyValue("classname", "target_relay");
					ent:SetKeyValue("targetname", "t389");
					ent:SetKeyValue("target", "sbportff");
					entity.CallSpawn(ent);
				game.Print("----setting up delay...");
					ent = entity.Spawn();
					ent:SetKeyValue("classname", "target_delay");
					ent:SetKeyValue("targetname", "t389");
					ent:SetKeyValue("target", "sbportff");
					ent:SetKeyValue("wait", "20");
					entity.CallSpawn(ent);
			game.Print("---Starbord...");
				game.Print("----Converting...");
					ent = entity.FindBModel(111);
					ent:SetKeyValue("classname", "func_forcefield");
					ent:SetKeyValue("targetname", "sbstbdff");
					ent:SetKeyValue("wait", "200");
					entity.CallSpawn(ent);
				game.Print("----setting up relay...");
					ent = entity.Spawn();
					ent:SetKeyValue("classname", "target_relay");
					ent:SetKeyValue("targetname", "t388");
					ent:SetKeyValue("target", "sbstbdff");
					entity.CallSpawn(ent);
				game.Print("----setting up delay...");
					ent = entity.Spawn();
					ent:SetKeyValue("classname", "target_delay");
					ent:SetKeyValue("targetname", "t388");
					ent:SetKeyValue("target", "sbstbdff");
					ent:SetKeyValue("wait", "20");
					entity.CallSpawn(ent);   
		game.Print("--Transporter Room..."); 
			ent = entity.FindBModel(43);
			ent:SetKeyValue("classname", "func_forcefield");
			entity.CallSpawn(ent); 
			ent = entity.FindBModel(239);
			entity.Remove(ent);  
		game.Print("--Transporter Room..."); 
			ent = entity.FindBModel(203);
			ent:SetKeyValue("classname", "func_forcefield");
			entity.CallSpawn(ent); 
			ent = entity.FindBModel(238);
			entity.Remove(ent);      ]]--  
	game.Print("-Adding weapon FX ...");
		game.Print(".--usable setup ...");
			ent = entity.FindBModel(174);
			ent:SetKeyValue("target", "phaser-vfx");
			ent = entity.FindBModel(175);
			ent:SetKeyValue("target", "torpedo-vfx");
		game.Print("--Torpedo-Relay ...");
			ent = entity.Spawn();
			ent:SetKeyValue("classname", "target_relay");
			ent:SetKeyValue("target", "torpedo-vfx-relayed");
			ent:SetKeyValue("spawnflags", "8");
			ent:SetKeyValue("targetname", "torpedo-vfx");
			entity.CallSpawn(ent);
		game.Print("--Bridge ...");
			game.Print("---target setup ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "weapTrgD1");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, 320, -1766, 4032);
			game.Print("---Phaser ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "fx_phaser");
				ent:SetKeyValue("target", "weapTrgD1");
				ent:SetKeyValue("targetname", "phaser-vfx");
				ent:SetKeyValue("wait", "3");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, 56, -1766, 4152);
			game.Print("---Torpedo ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "fx_torpedo");
				ent:SetKeyValue("target", "weapTrgD1");
				ent:SetKeyValue("wait", "1");
				ent:SetKeyValue("count", "500");
				ent:SetKeyValue("speed", "1");
				ent:SetKeyValue("targetname", "torpedo-vfx");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, 56, -1766, 4152);
		game.Print("--Messhall ...");
			game.Print("---target setup ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "info_notnull");
				ent:SetKeyValue("targetname", "weapTrgD2");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, 1472, -1782, 3840);
			game.Print("---Phaser ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "fx_phaser");
				ent:SetKeyValue("target", "weapTrgD2");
				ent:SetKeyValue("targetname", "phaser-vfx");
				ent:SetKeyValue("wait", "3");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, 456, -1782, 3808);
			game.Print("---Torpedo ...");
				ent = entity.Spawn();
				ent:SetKeyValue("classname", "fx_torpedo");
				ent:SetKeyValue("target", "weapTrgD2");
				ent:SetKeyValue("wait", "1");
				ent:SetKeyValue("count", "500");
				ent:SetKeyValue("targetname", "torpedo-vfx-relayed");
				entity.CallSpawn(ent);
				mover.SetPosition(ent, 456, -1782, 3808);  
	game.Print("-Intensive Care Lockdown ...")
		game.Print("--usable fit ...");
			ent = entity.FindBModel(205);
			ent:SetLuaUse("sicklock");
			entity.CallSpawn(ent)
	game.Print("-Auxillary Transporter Room Lockoff ...")
		game.Print("--left door...");
			ent = entity.FindBModel(82);
			ent:SetKeyValue("targetname", "auxtrdoor"); 
			ent.Lock(ent);
			entity.CallSpawn(ent);  
		game.Print("--rigth door...");
			ent = entity.FindBModel(81);
			ent:SetKeyValue("targetname", "auxtrdoor"); 
			ent.Lock(ent);
			entity.CallSpawn(ent);
	game.Print("Done...");
end        

function sicklock ( ent , other , activator )
	ent = entity.FindBModel(202);
	if ent.Is Locked(ent) == true then
	ent.Unlock(ent);
	else
	ent.Lock(ent);
end
	